import {
	ArrowLeftRight,
	Banknote,
	Briefcase,
	Bus,
	Car,
	ChefHat,
	CircleDollarSign,
	Coffee,
	CreditCard,
	Dumbbell,
	Film,
	Fuel,
	Gamepad2,
	Gift,
	GraduationCap,
	Heart,
	HeartPulse,
	Home,
	KeyRound,
	Landmark,
	Laptop,
	Lightbulb,
	MapPin,
	Music,
	Phone,
	Pill,
	Pizza,
	Plane,
	Receipt,
	Repeat,
	Shield,
	ShieldCheck,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	Sparkles,
	Stethoscope,
	TrainFront,
	TrendingUp,
	Tv,
	Utensils,
	Wallet,
	Wifi,
	Wrench,
	Zap,
	PawPrint,
	Cross,
	type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
	"arrow-left-right": ArrowLeftRight,
	"banknote": Banknote,
	"briefcase": Briefcase,
	"bus": Bus,
	"car": Car,
	"chef-hat": ChefHat,
	"circle-dollar-sign": CircleDollarSign,
	"coffee": Coffee,
	"credit-card": CreditCard,
	"dumbbell": Dumbbell,
	"film": Film,
	"fuel": Fuel,
	"gamepad-2": Gamepad2,
	"gift": Gift,
	"graduation-cap": GraduationCap,
	"heart": Heart,
	"heart-pulse": HeartPulse,
	"home": Home,
	"key-round": KeyRound,
	"landmark": Landmark,
	"laptop": Laptop,
	"lightbulb": Lightbulb,
	"map-pin": MapPin,
	"music": Music,
	"phone": Phone,
	"pill": Pill,
	"pizza": Pizza,
	"plane": Plane,
	"receipt": Receipt,
	"repeat": Repeat,
	"shield": Shield,
	"shield-check": ShieldCheck,
	"shopping-bag": ShoppingBag,
	"shopping-cart": ShoppingCart,
	"smartphone": Smartphone,
	"sparkles": Sparkles,
	"stethoscope": Stethoscope,
	"train-front": TrainFront,
	"trending-up": TrendingUp,
	"tv": Tv,
	"utensils": Utensils,
	"wallet": Wallet,
	"wifi": Wifi,
	"wrench": Wrench,
	"zap": Zap,
	"paw-print": PawPrint,
	"cross": Cross,
} as const

export type { LucideIcon }
